### ISSUE TITLE
How to ignore space diff?

### ISSUE THREAD

**Issue by yibingxiong** [babel-utils/babel-plugin-tester#51]
When I test my plugin width babel-plugin-tester, I found the output and expected were only have difference of space. Could you tell me how to ignore the diff caused by space? THX.

**Comment by kentcdodds** [comment]
Could you show me an example of what you mean?

**Comment by yibingxiong** [comment]
like this, the expected value and received only has diff of space.
```
Expected value to be equal to:
      "function A() {
        var tset = 1;
    }"
    Received:
      "function A() {
      var tset = 1;
    }"
    
    Message:
      Output is incorrect.

    Difference:

    - Expected
    + Received

      function A() {
    -     var tset = 1;
    +   var tset = 1;
      }
```

**Comment by kentcdodds** [comment]
What does your test look like?

**Comment by yibingxiong** [comment]
like this. THX.
```
// index.test.js
const pluginTester = require('babel-plugin-tester')
const path = require('path');

function Plugin() {
  const visitor = {
      Identifier(path, state) {
          let name = path.node.name;
          path.node.name = name.split('').reverse().join('');
      },
  }
  return {
      name: 'test',
      visitor,
  }
}

pluginTester({
    plugin: Plugin,
    tests: {
      'changes this code': {
        fixture: path.join(__dirname, '__fixtures__/changed.js'),
         outputFixture: path.join(__dirname, '__fixtures__/changed-output.js'),
      },
    },
  })

// __fixtures__/changed.js
function A () {
    var test = 1;
}

// __fixtures__/changed-output.js
function A() {
    var tset = 1;
}
```

**Comment by kentcdodds** [comment]
Gotcha. Hmmm... I think that the problem is babel doesn't honor your original format when you make changes to the AST, so instead of 4 spaces, it changes to 2 spaces.

One thing you could consider is using the `formatResult` option which would allow you to format the result with prettier (for example). Or, you could update your output file to match the whitespace that babel leaves it with. Or you could just use the snapshot option instead and not bother keeping the output updated manually.

Whatever you choose, I'm afraid there's nothing we can do in this package to make this work the way you want it to. Sorry. Good luck!

**Comment by yibingxiong** [comment]
Oh, I see. I used snapshots finally. Very convenient. THX!
