### ISSUE TITLE
Issue with Babel `declare(...)` Api-Check Helper

### ISSUE THREAD

**Issue by JohnPucciarelli** [babel-utils/babel-plugin-tester#60]
- `babel-plugin-tester` version: 7.8.3
- `node` version: v12.14.0
- `npm` (or `yarn`) version: npm@6.13.6

---

When using the `declare(...)` helper from `@babel/helper-plugin-utils`, the `api.assertVersion(...)` call gives me the following error:

```sh
  ● Test suite failed to run

    Requires Babel "^7.0.0-beta.41", but was loaded with "7.8.4". You'll need to update your @babel/core version.

      18 | export default declare((api, options, dirname) => {
      19 |   // check babel version
    > 20 |   api.assertVersion(7);
```

If you look at the error message, my `@babel/core` version is ahead of the minimum requirement. I believe this is the result of some incompatibility between the `declare(...)` helper and this library.

This message is not displayed if I switch to running my tests with `@babel/helper-plugin-test-runner`.

Please let me know if there's any additional information I can provide you with.

**Comment by kentcdodds** [comment]
Hi @JohnPucciarelli,

I'm not sure what's causing this error. I haven't used the `declare` helper before, so I don't have any insight for you. If you'd like to dig a little further and suggest a solution then I'd be happy to review that :) Otherwise, I'm afraid I don't have the bandwidth to dig into this myself. Sorry.

**Comment by kentcdodds** [comment]
Didn't mean to close that 😬 Sorry!

**Comment by JohnPucciarelli** [comment]
Thanks for the response @kentcdodds,

I looked into the issue some more and found out the following:

It seems that most, if not all, the official babel plugins use the `declare(...)` helper when defining a plugin - [example here](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-exponentiation-operator/src/index.js#L5).

That helper checks for the presence of an `assertVersion(...)` property/function attached to the babel api object. If it's present, it does nothing but calls the plugin. However, if `assertVersion` is missing, it attaches a similar check. This is useful for older versions of babel that don't have that version check present - [`declare(...)` source here](https://github.com/babel/babel/blob/master/packages/babel-helper-plugin-utils/src/index.js)

I logged the output of the api object passed into my plugin by babel-plugin-tester and it seems to be missing that `assertVersion` function (output below).

Adding the `assertVersion(...)` property/function to the babel api object passed to the plugin would fix this issue. The function is available here - [built-in `assertVersion(...)`](https://github.com/babel/babel/blob/master/packages/babel-core/src/config/helpers/config-api.js#L62)

Unfortunately, I'm not too familiar with the source of this project. This issue is non-blocking as the `api.assertVersion(...)` check isn't required by plugins but it seems encouraged.

**Output of Babel Api Object**
```
{
      Plugin: [Function: Plugin],
      File: [Getter],
      buildExternalHelpers: [Getter],
      resolvePlugin: [Getter],
      resolvePreset: [Getter],
      version: [Getter],
      getEnv: [Getter],
      tokTypes: [Getter],
      traverse: [Getter],
      template: [Getter],
      createConfigItem: [Getter],
      loadPartialConfig: [Getter],
      loadPartialConfigSync: [Getter],
      loadPartialConfigAsync: [Getter],
      loadOptions: [Getter],
      loadOptionsSync: [Getter],
      loadOptionsAsync: [Getter],
      transform: [Getter],
      transformSync: [Getter],
      transformAsync: [Getter],
      transformFile: [Getter],
      transformFileSync: [Getter],
      transformFileAsync: [Getter],
      transformFromAst: [Getter],
      transformFromAstSync: [Getter],
      transformFromAstAsync: [Getter],
      parse: [Getter],
      parseSync: [Getter],
      parseAsync: [Getter],
      DEFAULT_EXTENSIONS: [ '.js', '.jsx', '.es6', '.es', '.mjs' ],
      OptionManager: [Function: OptionManager],
      types: [Getter]
    }
```

Hopefully that helps explain what I ran into and helps anyone else running into a similar issue.

**Comment by kentcdodds** [comment]
Yeah sorry, I just don't have the bandwidth to look into this myself at the moment. But thank you for your investigation. If anyone else would like to dive in further to determine a good solution that would be great 👍

**Comment by jayphelps** [comment]
FYI the issue is that babel 7 started providing the ConfigAPI object, the same one usually provided to babel.config.js files, to plugins too. So it's not the same thing as the old regular 'babel' namespace. When this helper library calls the plugin function with the old argument, it fails because the declare() helper in v7 checks whether assertVersion is missing, and if it is makes the assumption you're using a older version of babel.

If it's not easy to make a ConfigAPI object, a simple workaround for this library would be to stub out assertVersion with a noop.

I also wanted to note that Ken's suggested workaround in https://github.com/babel-utils/babel-plugin-tester/issues/58#issuecomment-579385441 did the trick for me--this library will skip calling your plugin directly, so the problem no longer applies.

**Comment by kentcdodds** [comment]
Maybe we should make the pluginName required and not do the inference?

**Comment by jayphelps** [comment]
@kentcdodds that seems reasonable to me.

**Comment by jayphelps** [comment]
Thanks for fixing!
